workflows:
  expo-development-build:
    name: Expo Development Build (Android & iOS)
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        BUILD_NUMBER: "1"
        XCODE_WORKSPACE: "ios/simpleiostodo.xcworkspace"
        XCODE_SCHEME: "simpleiostodo"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
      node: 20
      java: 17
      xcode: 15.0
      cocoapods: default

    cache:
      cache_paths:
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged
        - ~/Library/Caches/CocoaPods
        # Remove ios/Pods from cache to force fresh install
        # - ios/Pods

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: Setup Environment
        script: |
          echo "--- Environment Setup ---"
          node -v
          yarn -v
          npm -v
          java -version
          xcodebuild -version
          pod --version
          echo $ANDROID_SDK_ROOT

      - name: Clean and Install Dependencies
        script: |
          npm cache clean --force
          yarn install --network-timeout 600000 --ignore-engines

      - name: Setup EAS CLI
        script: |
          npm install -g eas-cli@latest --no-audit --fund=false --omit=optional
          npx eas-cli --version

      - name: Expo Prebuild (Android)
        script: |
          echo "--- Prebuild for Android ---"
          npx expo prebuild --platform android --non-interactive --clear
          ls -la android/

      - name: Build Android Development APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean :app:assembleDebug --no-daemon --stacktrace
          cd ..
          echo "--- APK Build Complete ---"

      - name: Clean iOS Build Environment
        script: |
          echo "--- Cleaning iOS Environment ---"
          rm -rf ios/Pods ios/Podfile.lock
          pod cache clean --all

      - name: Expo Prebuild (iOS)
        script: |
          echo "--- Prebuild for iOS ---"
          npx expo prebuild --platform ios --non-interactive --clear
          ls -la ios/

      - name: Install CocoaPods with Retry Logic
        script: |
          cd ios
          # Try installing pods with retry logic
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "--- Pod Install Attempt $attempt ---"
            
            if pod install --repo-update --verbose; then
              echo "--- Pod Install Successful ---"
              break
            else
              echo "--- Pod Install Failed (Attempt $attempt) ---"
              
              if [ $attempt -eq $max_attempts ]; then
                echo "--- All Pod Install Attempts Failed ---"
                exit 1
              fi
              
              # Clean up and try again
              rm -rf Pods Podfile.lock
              pod cache clean --all
              pod repo update
              
              attempt=$((attempt + 1))
              sleep 30
            fi
          done
          
          cd ..

      - name: Build iOS Development Version
        script: |
          # Create export options plist if it doesn't exist
          if [ ! -f ios/exportOptions.plist ]; then
            cat > ios/exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF
          fi

          # Build archive
          set -o pipefail && xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -archivePath ios/build/App.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty || true

          # Export IPA
          xcodebuild \
            -exportArchive \
            -archivePath ios/build/App.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath ios/build/Debug \
            CODE_SIGNING_ALLOWED=NO \
            | tee xcodebuild.log

          mkdir -p build_logs
          mv xcodebuild.log build_logs/ || true

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/**/*.log
      - ios/build/**/*.ipa
      - build_logs/xcodebuild.log
      - ios/build/**/*.log

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"