workflows:
  expo-multi-platform-build:
    name: Expo Multi-Platform Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "1"
        ANDROID_PROJECT_DIR: "android"
        ANDROID_BUILD_TYPE: "Debug"
        XCODE_WORKSPACE: "ios/simpleiostodo.xcworkspace"
        XCODE_SCHEME: "simpleiostodo"
      node: 20
      xcode: 15.0

    cache:
      cache_paths:
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged
        - android/.gradle
        - $HOME/.gradle/caches
        - ios/Pods
        - ~/.cocoapods

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: Setup Environment
        script: |
          echo "--- Environment Setup ---"
          node -v
          yarn -v
          npm -v
          xcodebuild -version
          pod --version

      - name: Install Dependencies
        script: |
          echo "--- Installing Dependencies ---"
          npm cache clean --force
          yarn install --network-timeout 600000 --ignore-engines

      - name: Setup EAS CLI
        script: |
          echo "--- Installing EAS CLI ---"
          npm install -g eas-cli@latest
          npx eas-cli --version

      - name: Generate Native Code
        script: |
          echo "--- Generating Native Projects ---"
          CI=1 npx expo prebuild --platform all --clean
          
          echo "--- Verifying generated files ---"
          ls -la ios/
          ls -la android/

      - name: Install CocoaPods
        script: |
          echo "--- Installing CocoaPods ---"
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update --verbose
          cd ..

      - name: Verify Pods Installation
        script: |
          echo "--- Verifying Pods Installation ---"
          ls -la ios/Pods/Target\ Support\ Files/Pods-simpleiostodo/
          ls -la ios/Pods/

      - name: Build iOS (Direct)
        script: |
          echo "--- Building iOS Project Directly ---"
          mkdir -p build_logs/ios
          
          echo "--- Cleaning workspace ---"
          xcodebuild clean \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug
          
          echo "--- Starting build ---"
          set -o pipefail && xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            ONLY_ACTIVE_ARCH=NO \
            COMPILER_INDEX_STORE_ENABLE=NO \
            | tee build_logs/ios/xcodebuild.log
          
          BUILD_RESULT=$?
          
          if [ $BUILD_RESULT -ne 0 ]; then
            echo "--- Build Log (last 50 lines) ---"
            tail -n 50 build_logs/ios/xcodebuild.log
            echo "--- Available schemes ---"
            xcodebuild -workspace "$XCODE_WORKSPACE" -list
            exit 1
          else
            echo "✅ iOS build successful"
          fi

      - name: Build Android
        script: |
          echo "--- Building Android ---"
          cd android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --stacktrace
          cd ..
          echo "--- Built APKs ---"
          find android -name "*.apk" -exec ls -la {} \;

    artifacts:
      - build_logs/**/*
      - android/app/build/outputs/**/*.apk
      - ios/build/**/*

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com