workflows:
  react-native-app:
    name: React Native Build (iOS + Android)
    max_build_duration: 60
    environment:
      vars:
        PROJECT_DIR: "."  # path to your React Native project
        ANDROID_BUILD_DIR: "$PROJECT_DIR/android"
        IOS_BUILD_DIR: "$PROJECT_DIR/ios"
      flutter: stable
      node: latest
      xcode: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          npm install

      - name: Install CocoaPods dependencies (iOS)
        script: |
          cd $IOS_BUILD_DIR
          pod install

      - name: Build Android APK (unsigned)
        script: |
          cd $ANDROID_BUILD_DIR
          ./gradlew assembleDebug

      - name: Build iOS app (unsigned)
        script: |
          cd $IOS_BUILD_DIR
          xcodebuild -workspace YourApp.xcworkspace \
                     -scheme YourApp \
                     -configuration Debug \
                     -sdk iphoneos \
                     -derivedDataPath build

    artifacts:
      - android/app/build/outputs/**/*.apk
      - ios/build/Build/Products/**/*.app
