workflows:
  expo-ios-development:
    name: Expo iOS Development Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        BUILD_NUMBER: "1"
        RCT_NO_LAUNCH_PACKAGER: "true"
        RCT_METRO_PORT: "8081"
      node: 20
      java: 17

    cache:
      cache_paths:
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged
        - ios/Podfile.lock

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: Environment Setup
        script: |
          echo "--- System Information ---"
          sw_vers
          echo "--- Node $(node -v) ---"
          echo "--- Yarn $(yarn -v) ---"
          echo "--- Xcode $(xcodebuild -version | head -n 1) ---"
          echo "--- Ruby $(ruby -v) ---"
          echo "--- CocoaPods $(pod --version) ---"

      - name: Clean Workspace
        script: |
          echo "--- Cleaning previous builds ---"
          cd ios
          rm -rf Pods build DerivedData
          pod deintegrate || true
          cd ..

      - name: Install Dependencies
        script: |
          echo "--- Installing JS dependencies ---"
          yarn install --network-timeout 600000 --ignore-engines
          
          echo "--- Installing CocoaPods ---"
          cd ios
          pod install --repo-update --clean-install
          
          # Verify workspace was created
          if [ -d "simpleiostodo.xcworkspace" ]; then
            echo "Workspace generated successfully"
          else
            echo "No workspace generated, using project file"
          fi
          cd ..

      - name: Build Configuration
        script: |
          cd ios
          # Determine build command based on workspace existence
          if [ -d "simpleiostodo.xcworkspace" ]; then
            BUILD_CMD="-workspace simpleiostodo.xcworkspace"
          else
            BUILD_CMD="-project simpleiostodo.xcodeproj"
          fi
          
          echo "--- Building with command: xcodebuild $BUILD_CMD ---"
          set -o pipefail && xcodebuild \
            $BUILD_CMD \
            -scheme simpleiostodo \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            -UseModernBuildSystem=YES \
            CODE_SIGNING_ALLOWED=NO \
            clean build | tee xcodebuild.log
          cd ..

    artifacts:
      - ios/build/**/*
      - ios/xcodebuild.log
      - ios/Podfile.lock

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"