workflows:
  expo-ios-build:
    name: Expo iOS Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        XCODE_WORKSPACE: "ios/simple-ios-todo.xcworkspace"  # Expo generates this
        XCODE_SCHEME: "simple-ios-todo"                    # Your Expo app name
        BUNDLE_ID: "com.anonymous.simpleiostodo"           # From your app.json
      node: 18
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - $HOME/.npm
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    
    scripts:
      - name: Install Expo CLI
        script: |
          echo "--- Setting up Expo environment ---"
          npm install -g expo-cli eas-cli
          npm ci
          
      - name: Prebuild iOS files
        script: |
          echo "--- Generating iOS native files ---"
          eas prebuild --platform ios
          cd ios
          pod install --repo-update --verbose
          
      - name: Configure development build
        script: |
          echo "--- Configuring development build ---"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          
      - name: Build IPA
        script: |
          echo "--- Building Development IPA ---"
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --disable-codesigning

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/**/*.dSYM
    
    publishing:
      scripts:
        - name: Clean up
          script: |
            rm -rf ios/build
      email:
        recipients:
          - webdev.faizanali@gmail.com  # Change to your email