workflows:
  expo-ios-development:
    name: Expo iOS Development Build
    instance_type: mac_mini_m1
    working_directory: .
    environment:
      vars:
        XCODE_WORKSPACE: "ios/simple-ios-todo.xcworkspace"
        XCODE_SCHEME: "simple-ios-todo"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "1"
      node: 22
      xcode: 15.0
      # ruby: 3.4.4
      cocoapods: 1.14.2

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: System Dependencies
        script: |
          echo "--- Installing system dependencies ---"
          brew update
          brew install openssl@3 readline libyaml gmp gcc
          brew link openssl@3 --force
          echo "--- Compiler and OpenSSL info ---"
          which gcc
          ls -la $(brew --prefix openssl@3)/lib
          ls -la $(brew --prefix openssl@3)/include
          brew cleanup
          # Xcode setup
          xcode-select --install || true
          sudo xcodebuild -license accept || true

      - name: Install Ruby 3.1.4 (ARM64 Optimized)
        script: |
          echo "--- Installing Ruby 3.1.4 for M1 ---"
          export CC=/usr/bin/gcc
          export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3) --with-opt-dir=$(brew --prefix openssl@3)"
          export LDFLAGS="-L$(brew --prefix openssl@3)/lib -arch arm64"
          export CPPFLAGS="-I$(brew --prefix openssl@3)/include"
          export PKG_CONFIG_PATH="$(brew --prefix openssl@3)/lib/pkgconfig"
          export RUBY_CFLAGS="-Wno-error=implicit-function-declaration"
          export archflags="-arch arm64"

          echo "Compiler: $CC"
          echo "Configure opts: $RUBY_CONFIGURE_OPTS"
          echo "LDFLAGS: $LDFLAGS"
          
          rbenv install 3.1.4 -v || {
            echo "--- Fallback attempt with different settings ---"
            export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3) --disable-install-doc"
            rbenv install 3.1.4 -v
          }
          
          rbenv global 3.1.4
          ruby -v

      - name: Verify Ruby Installation
        script: |
          if ! ruby -v | grep "3.1.4"; then
            echo "❌ Ruby installation failed!"
            exit 1
          fi
          gem install bundler

      - name: Install Dependencies
        script: |
          echo "--- Cleaning caches ---"
          npm cache clean --force
          yarn cache clean
          echo "--- Installing dependencies ---"
          yarn install --network-timeout 600000 --frozen-lockfile

      - name: EAS CLI Setup
        script: |
          npm install -g eas-cli@latest
          eas --version

      - name: Expo Prebuild
        script: |
          echo "--- Generating native code ---"
          npx expo prebuild --platform ios --non-interactive
          echo "--- iOS directory structure ---"
          ls -la ios/

      - name: CocoaPods Setup
        script: |
          echo "--- Updating CocoaPods ---"
          gem install cocoapods -v 1.14.2 --user-install
          pod setup --verbose
          echo "--- Pod environment ---"
          pod env

      - name: Pod Installation (ARM64 Optimized)
        script: |
          echo "--- Preparing Pods ---"
          cd ios
          pod cache clean --all
          rm -rf Pods Podfile.lock
          echo "--- Podfile Content ---"
          cat Podfile || echo "No Podfile found"
          
          echo "--- Installing Pods (M1 optimized) ---"
          export GEM_HOME=$HOME/.gem
          export PATH=$GEM_HOME/bin:$PATH
          arch -arm64 pod install --repo-update --verbose
          
          echo "--- Pods directory ---"
          ls -la Pods/
          cd ..

      - name: Xcode Build (ARM64)
        script: |
          echo "--- Building archive ---"
          mkdir -p build
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/simple-ios-todo.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=YES \
            ARCHS=arm64

          echo "--- Exporting IPA ---"
          xcodebuild -exportArchive \
            -archivePath build/simple-ios-todo.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/export \
            ARCHS=arm64

          echo "--- Build artifacts ---"
          ls -la build/export/

    artifacts:
      - build/export/*.ipa
      - build_logs/**/*
      
    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"