workflows:
  expo-ios-development:
    name: Expo iOS Development Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        BUILD_NUMBER: "1"
      node: 20
      java: 17

    cache:
      cache_paths:
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged
        - ios/Pods
        - ios/Podfile.lock

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: Setup Environment
        script: |
          echo "--- Node version ---"
          node -v
          echo "--- Yarn version ---"
          yarn -v
          echo "--- npm version ---"
          npm -v
          echo "--- Xcode version ---"
          xcodebuild -version
          echo "--- Ruby version ---"
          ruby -v
          echo "--- CocoaPods version ---"
          pod --version

      - name: Clean Pods Installation
        script: |
          echo "--- Cleaning previous Pods installation ---"
          cd ios
          rm -rf Pods Podfile.lock simpleiostodo.xcworkspace
          cd ..

      - name: Install Dependencies
        script: |
          echo "--- Installing Yarn dependencies ---"
          yarn install --network-timeout 600000 --ignore-engines
          echo "--- Installing CocoaPods ---"
          cd ios
          pod install --repo-update --clean-install
          cd ..

      - name: Verify Pods Installation
        script: |
          echo "--- Verifying Pods files ---"
          cd ios
          if [ ! -f "Pods/Target Support Files/Pods-simpleiostodo/Pods-simpleiostodo.debug.xcconfig" ]; then
            echo "Pods configuration missing, reinstalling..."
            pod install --clean-install
          fi
          cd ..

      - name: Setup EAS CLI
        script: |
          npm install -g eas-cli@latest --no-audit --fund=false --omit=optional
          npx eas-cli --version

      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform ios --non-interactive
          echo "--- Fixing React Native Script Phases ---"
          cd ios
          # Fix for "Bundle React Native code and images" warning
          sed -i '' 's/Based on dependency analysis/AlwaysOutOfDate/g' simpleiostodo.xcodeproj/project.pbxproj
          cd ..

      - name: Build iOS
        script: |
          echo "--- Building iOS App ---"
          cd ios
          xcodebuild \
            -project simpleiostodo.xcodeproj \
            -scheme simpleiostodo \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build \
            -UseModernBuildSystem=YES \
            clean build | tee xcodebuild.log
          cd ..
          echo "--- Build Complete ---"

    artifacts:
      - ios/build/**/*
      - ios/xcodebuild.log
      - ios/Podfile.lock
      - ios/Pods/Manifest.lock

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"