workflows:
  expo-ios-production:
    name: Expo iOS Production Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        XCODE_WORKSPACE: "ios/simple-ios-todo.xcworkspace"
        XCODE_SCHEME: "simple-ios-todo"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
      node: 18
      xcode: 15.0
      cocoapods: default
    
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - $HOME/.yarn/cache
        - $HOME/.yarn/berry/cache
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    
    scripts:
      - name: Install Yarn and dependencies
        script: |
          echo "--- Setting up Yarn ---"
          npm install -g yarn
          yarn set version stable
          yarn install --frozen-lockfile --network-timeout 600000
          yarn global add expo-cli eas-cli
          
      - name: Expo Prebuild
        script: |
          echo "--- Generating iOS Native Code ---"
          eas prebuild --platform ios --non-interactive
          
      - name: Install CocoaPods
        script: |
          echo "--- Installing Pods ---"
          cd ios
          pod install --repo-update --verbose
          
      - name: Configure Build
        script: |
          echo "--- Configuring Build ---"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          
      - name: Build IPA
        script: |
          echo "--- Building Production IPA ---"
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --disable-codesigning

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/**/*.dSYM
    
    publishing:
      scripts:
        - name: Clean up build artifacts
          script: rm -rf ios/build
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"