workflows:
  expo-ios-production:
    name: Expo iOS Production Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        APP_NAME: "simple-ios-todo" # Must match your app name
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "$(date +%Y%m%d%H%M)"
        TEAM_ID: "YOUR_APPLE_TEAM_ID" # REQUIRED: Get from Apple Developer Account
        EXPO_PACKAGE: "expo@latest" # Ensures correct expo version
      node: 20
      xcode: 15.0
      cocoapods: default

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache

    scripts:
      - name: Environment Setup
        script: |
          echo "=== SYSTEM INFO ==="
          echo "Node: $(node -v)"
          echo "Yarn: $(yarn -v)"
          echo "npm: $(npm -v)"
          echo "Ruby: $(ruby -v)"
          echo "CocoaPods: $(pod --version)"
          
          # Clean environment
          npm cache clean --force
          yarn cache clean
          rm -rf ios/build
          rm -rf node_modules/expo

      - name: Install Dependencies
        script: |
          echo "--- Installing Exact Expo Version ---"
          yarn add $EXPO_PACKAGE --exact
          
          echo "--- Installing Project Dependencies ---"
          yarn install --network-timeout 600000 --frozen-lockfile
          
          echo "--- Installing EAS CLI ---"
          npm install -g eas-cli@latest --no-audit

      - name: Generate Native Code (Fixed)
        script: |
          echo "--- Cleaning Previous Builds ---"
          rm -rf ios ios/.xcode.env
          
          echo "--- Running Prebuild ---"
          npx expo prebuild --platform ios --non-interactive --clear-cache || {
            echo "Prebuild failed, attempting repair..."
            rm -rf ios
            npx expo-doctor --fix-dependencies
            npx expo prebuild --platform ios --non-interactive
          }
          
          echo "--- Verifying Output ---"
          if [ ! -d "ios" ]; then
            echo "iOS folder not generated!"
            exit 1
          fi

      - name: iOS Configuration
        script: |
          echo "--- Installing CocoaPods ---"
          cd ios
          pod install --repo-update --verbose
          
          echo "--- Setting Build Version ---"
          agvtool new-version -all $BUILD_NUMBER
          
          echo "--- Generating Export Options ---"
          cat > ExportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOL
          cd ..

      - name: Build IPA
        script: |
          echo "--- Building IPA ---"
          cd ios
          mkdir -p build
          
          xcodebuild archive \
            -workspace "$APP_NAME.xcworkspace" \
            -scheme "$APP_NAME" \
            -configuration Release \
            -archivePath build/$APP_NAME.xcarchive \
            -allowProvisioningUpdates
          
          xcodebuild -exportArchive \
            -archivePath build/$APP_NAME.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa \
            -allowProvisioningUpdates

    artifacts:
      - ios/build/ipa/*.ipa
      - ios/build/**/*.dSYM

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"