workflows:
  expo-multi-platform-build:
    name: Expo Multi-Platform Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        # iOS specific vars
        XCODE_WORKSPACE: "ios/SimpleTodo.xcworkspace"
        XCODE_SCHEME: "SimpleTodo"
        BUNDLE_ID: "com.anonymous.simpletodo"
        BUILD_NUMBER: "1"
        
        # Android specific vars
        ANDROID_PROJECT_DIR: "android"
        ANDROID_BUILD_TYPE: "Debug"
      node: 20
      xcode: 15.0
      cocoapods: default

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged
        - android/.gradle
        - $HOME/.gradle/caches

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: Setup Environment
        script: |
          echo "--- Node version ---"
          node -v
          echo "--- Yarn version ---"
          yarn -v
          echo "--- npm version ---"
          npm -v
          echo "--- Xcode version ---"
          xcodebuild -version
          echo "--- CocoaPods version ---"
          pod --version
          echo "--- Java version ---"
          java -version

      - name: Install Dependencies
        script: |
          echo "--- Cleaning npm cache ---"
          npm cache clean --force
          echo "--- Installing Yarn dependencies ---"
          yarn install --network-timeout 600000 --ignore-engines

      - name: Setup EAS CLI
        script: |
          echo "--- Installing EAS CLI ---"
          npm install -g eas-cli@latest --no-audit --fund=false --omit=optional
          echo "--- EAS CLI version ---"
          npx eas-cli --version

      - name: Expo Prebuild
        script: |
          echo "--- Generating Native Code ---"
          npx expo prebuild --platform all --non-interactive
          echo "--- Prebuild contents verification ---"
          ls -la ios/
          ls -la android/

      - name: Install CocoaPods (iOS)
        script: |
          echo "--- Installing Pods ---"
          cd ios
          pod install --repo-update --verbose
          cd ..
          echo "--- Pods directory contents ---"
          ls -la ios/Pods/

      - name: Build iOS Debug Version
        script: |
          echo "--- Building iOS Debug Version ---"
          set -o pipefail && xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -quiet \
            CODE_SIGNING_ALLOWED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO \
            | xcpretty

          # Save logs if the build fails
          mkdir -p build_logs/ios
          mv /var/folders/*/T/ResultBundle_* build_logs/ios/ || true

      - name: Build Android Debug Version
        script: |
          echo "--- Building Android Debug Version ---"
          cd android
          ./gradlew assembleDebug --stacktrace
          cd ..
          echo "--- APK location ---"
          find android -name "*.apk" -exec ls -la {} \;

    artifacts:
      - build_logs/**/*
      - ios/build/**/*.log
      - android/app/build/outputs/**/*.apk
      - ios
      - android

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"