workflows:
  react-native-ios-android-unsigned:
    name: React Native iOS and Android Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: 15.4
      java: 17
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies and prebuild
        script: |
          yarn install --legacy-peer-deps
          npx expo prebuild
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS app unsigned (skip signing)
        script: |
          xcodebuild -workspace ios/Bluesky.xcworkspace \
            -scheme Bluesky \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath build
          # This will build the app but not sign it for distribution
      - name: Build Android app unsigned (debug build)
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - build/ios/Build/Products/Debug-iphonesimulator/*.app
      - android/app/build/outputs/apk/debug/*.apk
