workflows:
  ios-prebuild:
    name: Expo iOS without Expo login
    environment:
      vars:
        APP_NAME: "simple-ios-todo"
        SCHEME: "simpleiostodo"
        WORKSPACE: "ios/simpleiostodo.xcworkspace"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
      node: 18
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Convert Expo to bare React Native project
        script: |
          npx expo prebuild --platform ios --clean --no-install
      - name: Install CocoaPods
        script: |
          cd ios && pod install && cd ..
      - name: Build iOS app with Xcode
        script: |
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/$SCHEME.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/$SCHEME.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported
    artifacts:
      - $CM_BUILD_DIR/exported/*.ipa
      - $CM_BUILD_DIR/exported/*.dSYM.zip
    publishing:
      email:
        recipients:
          - your_email@example.com
