# Codemagic CI/CD configuration for Expo iOS development builds
# This configuration builds an iOS development version of an Expo project

# Workflow definitions
workflows:
  expo-ios-development:
    name: Expo iOS Development Build
    instance_type: mac_mini_m2  # Use M2 Mac mini for better performance
    working_directory: .  # Root directory of the project
    environment:
      # Environment variables
      vars:
        XCODE_WORKSPACE: "ios/simple-ios-todo.xcworkspace"
        XCODE_SCHEME: "simple-ios-todo"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "1"
      # Software versions
      node: 20
      xcode: 15.1
      cocoapods: default
    # Expo CLI version (simplified format)
    cli: latest

# Build configuration for iOS
build:
  ios:
    image: macos-latest  # Base image
    shell: bash  # Default shell
    env:
      # Node.js memory configuration
      NODE_OPTIONS: --max_old_space_size=4096

    # Prebuild phase - runs before dependencies are installed
    prebuild:
      - echo "--- Running expo prebuild for iOS ---"
      - CI=1 npx expo prebuild --platform ios

    # Postinstall phase - runs after dependencies are installed
    postinstall:
      - echo "--- Cleaning old CocoaPods ---"
      - cd ios
      - rm -rf Pods Podfile.lock
      - pod deintegrate || true  # Continue if this fails
      - echo "--- Installing CocoaPods with arch workaround ---"
      - arch -x86_64 pod install --repo-update

    # Cache configuration to speed up subsequent builds
    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged

    # When the build should trigger
    triggering:
      events:
        - push  # Trigger on git push
      branch_patterns:
        - pattern: "master*"  # Only build master branch
          include: true
          source: true

    # Build scripts (executed in order)
    scripts:
      # 1. Environment setup
      - name: Setup Environment
        script: |
          echo "--- Node version ---"
          node -v
          echo "--- Yarn version ---"
          yarn -v
          echo "--- npm version ---"
          npm -v
          echo "--- Xcode version ---"
          xcodebuild -version
          echo "--- CocoaPods version ---"
          pod --version

      # 2. Xcode and CocoaPods setup
      - name: Setup Xcode and CocoaPods
        script: |
          echo "--- Selecting full Xcode developer directory ---"
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          echo "--- Verifying xcode-select path ---"
          xcode-select -p

          echo "--- Installing/Updating CocoaPods gem ---"
          sudo gem install cocoapods

          # Alternative installation via Homebrew (commented out)
          # echo "--- Uninstalling CocoaPods gem (if present) ---"
          # sudo gem uninstall cocoapods || true
          # echo "--- Installing CocoaPods via Homebrew ---"
          # brew install cocoapods
          # echo "--- Linking CocoaPods binaries (if needed) ---"
          # brew link --overwrite cocoapods

          echo "--- Verifying CocoaPods version ---"
          pod --version

      # 3. JavaScript dependencies
      - name: Install Dependencies
        script: |
          echo "--- Cleaning npm cache ---"
          npm cache clean --force
          echo "--- Installing Yarn dependencies ---"
          yarn install --network-timeout 600000 --ignore-engines

          echo "--- Ensuring expo is installed ---"
          yarn add expo
          echo "--- Updating Pods ---"
          cd ios && arch -x86_64 pod install --repo-update && cd ..

      # 4. Expo prebuild (generates native code)
      - name: Expo Prebuild
        script: |
          echo "--- Generating iOS Native Code ---"
          CI=1 npx expo prebuild --platform ios
          echo "--- Prebuild contents verification ---"
          if [ -d "ios" ]; then
            echo "✅ iOS folder exists"
            ls -la ios/
          else
            echo "❌ iOS folder does not exist"
            exit 1
          fi

      # 5. EAS CLI setup (for Expo Application Services)
      - name: Setup EAS CLI
        script: |
          echo "--- Installing EAS CLI ---"
          npm install -g eas-cli@latest --no-audit --fund=false --omit=optional
          echo "--- EAS CLI version ---"
          npx eas-cli --version

      # 6. Final CocoaPods installation
      - name: Install CocoaPods
        script: |
          echo "--- Installing Pods ---"
          cd ios
          pod install --repo-update --verbose
          cd ..
          echo "--- Pods directory contents ---"
          ls -la ios/Pods/

    # Uncomment this section to enable the actual Xcode build
    #   - name: Build Development Version
    #     script: |
    #       echo "--- Building Development Version ---"
    #       set -o pipefail && xcodebuild \
    #         -workspace "$XCODE_WORKSPACE" \
    #         -scheme "$XCODE_SCHEME" \
    #         -configuration Debug \
    #         -destination 'generic/platform=iOS' \
    #         -quiet \
    #         CODE_SIGNING_ALLOWED=NO \
    #         COMPILER_INDEX_STORE_ENABLE=NO \
    #         | xcpretty
    #
    #       # Alternative approach if the above fails
    #       echo "--- Fallback: Detailed build logs ---"
    #       xcodebuild \
    #         -workspace "$XCODE_WORKSPACE" \
    #         -scheme "$XCODE_SCHEME" \
    #         -configuration Debug \
    #         -destination 'generic/platform=iOS' \
    #         CODE_SIGNING_ALLOWED=NO \
    #         | tee xcodebuild.log

    # Uncomment this section to enable artifact publishing
    # artifacts:
    #   - build/ios/ipa/*.ipa
    #   - /tmp/xcodebuild_logs/*.log
    #   - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    #   - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    #   - ios/build/**/*.log

    # Uncomment this section to enable notifications
    # publishing:
    #   email:
    #     recipients:
    #       - your-email@example.com
    #   slack:
    #     channel: "#build-notifications"