---
workflows:
  expo-multi-platform-build:
    name: Expo Multi-Platform Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "1"
        ANDROID_PROJECT_DIR: "android"
        ANDROID_BUILD_TYPE: "Debug"
        XCODE_WORKSPACE: "ios/simpleiostodo.xcworkspace"
        XCODE_SCHEME: "simpleiostodo"
      node: 20
      xcode: 15.0
      cocoapods: default

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged
        - android/.gradle
        - $HOME/.gradle/caches

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: Setup Environment
        script: |
          echo "--- Node version ---"
          node -v
          echo "--- Yarn version ---"
          yarn -v
          echo "--- npm version ---"
          npm -v
          echo "--- Xcode version ---"
          xcodebuild -version
          echo "--- CocoaPods version ---"
          pod --version
          echo "--- Java version ---"
          java -version

      - name: Install Dependencies
        script: |
          echo "--- Cleaning npm cache ---"
          npm cache clean --force
          echo "--- Installing Yarn dependencies ---"
          yarn install --network-timeout 600000 --ignore-engines

      - name: Setup EAS CLI
        script: |
          echo "--- Installing EAS CLI ---"
          npm install -g eas-cli@latest --no-audit --fund=false --omit=optional
          echo "--- EAS CLI version ---"
          npx eas-cli --version

      - name: Expo Prebuild
        script: |
          echo "--- Generating Native Code ---"
          npx expo prebuild --platform all --non-interactive --clean
          echo "--- Prebuild contents verification ---"
          ls -la ios/

      - name: Install CocoaPods (iOS)
        script: |
          echo "--- Cleaning previous Pods installation ---"
          rm -rf ios/Pods ios/Podfile.lock ios/simpleiostodo.xcworkspace
          
          echo "--- Installing Pods ---"
          cd ios
          pod install --repo-update --verbose
          cd ..
          
          echo "--- Verifying Pods installation ---"
          if [ -d "ios/Pods" ]; then
            echo "✅ Pods installed successfully"
          else
            echo "❌ Pods installation failed"
            exit 1
          fi
          
          echo "--- Checking workspace ---"
          if [ -d "ios/simpleiostodo.xcworkspace" ]; then
            echo "✅ Workspace created successfully"
          else
            echo "⚠️ Workspace not found, falling back to xcodeproj"
            if [ -d "ios/simpleiostodo.xcodeproj" ]; then
              echo "ℹ️ Using xcodeproj instead"
              echo "XCODE_PROJECT=ios/simpleiostodo.xcodeproj" >> $CM_ENV
              echo "USE_PROJECT=true" >> $CM_ENV
            else
              echo "❌ No valid Xcode project found!"
              exit 1
            fi
          fi

      - name: Prepare iOS Build
        script: |
          echo "--- Preparing iOS Build ---"
          cd ios
          xcodebuild clean -workspace simpleiostodo.xcworkspace -scheme simpleiostodo
          cd ..
          rm -rf ios/build

      - name: Build iOS Debug Version
        script: |
          echo "--- Building iOS Debug Version ---"
          mkdir -p build_logs/ios
          
          # Determine build target
          if [ "$USE_PROJECT" = "true" ] && [ -d "$XCODE_PROJECT" ]; then
            echo "Using Xcode project: $XCODE_PROJECT"
            BUILD_TARGET="-project $XCODE_PROJECT"
          elif [ -d "$XCODE_WORKSPACE" ]; then
            echo "Using workspace: $XCODE_WORKSPACE"
            BUILD_TARGET="-workspace $XCODE_WORKSPACE"
          else
            echo "Error: No valid workspace or project found"
            exit 1
          fi
          
          # Run the build with full logging
          set -o pipefail && xcodebuild \
            $BUILD_TARGET \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO \
            -UseModernBuildSystem=NO \
            | tee build_logs/ios/xcodebuild.log
          
          BUILD_RESULT=$?
          
          # Save build artifacts
          if ls /var/folders/*/T/ResultBundle_* 1> /dev/null 2>&1; then
            mv /var/folders/*/T/ResultBundle_* build_logs/ios/ || true
          fi
          
          # Print last 100 lines of log if build failed
          if [ $BUILD_RESULT -ne 0 ]; then
            echo "--- Last 100 lines of build log ---"
            tail -n 100 build_logs/ios/xcodebuild.log
            echo "--- Build failed with error code $BUILD_RESULT ---"
          fi
          
          exit $BUILD_RESULT

      - name: Build Android Debug Version
        script: |
          echo "--- Building Android Debug Version ---"
          cd android
          ./gradlew assembleDebug --stacktrace
          cd ..
          echo "--- APK location ---"
          find android -name "*.apk" -exec ls -la {} \;

    artifacts:
      - build_logs/**/*
      - ios/build/**/*.log
      - ios/build/**/*.xcactivitylog
      - ios/Podfile.lock
      - ios/Pods/Manifest.lock
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"