ios:
  release:
    name: iOS release
    <<: *instance_mac_m2
    environment:
      <<: *automatic_ios_signing
      <<: *env_versions
      vars:
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        XCODE_CONFIG: "Release"
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - *increment_ios_build_number
      - *build_ipa
    artifacts:
      - *ipa
      - *dsym
    publishing:
      <<: *email_release
      <<: *ios_app_store_publish

  staging:
    name: iOS develop
    <<: *instance_mac_m2
    environment:
      <<: *automatic_ios_signing
      <<: *env_versions
      vars:
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        XCODE_CONFIG: "Debug"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
    scripts:
      - *ios_initialize_keychain
      - *fetch_signing_files
      - *add_certs_to_keychain
      - *use_profiles
      - *increment_ios_build_number
      - *build_ipa
    artifacts:
      - *ipa
      - *xcode_log
    publishing:
      <<: *email_develop
      <<: *slack_publish
