workflows:
  react-native-app:
    name: React Native Build (iOS + Android)
    max_build_duration: 60
    environment:
      vars:
        PROJECT_DIR: "."
        ANDROID_BUILD_DIR: "$PROJECT_DIR/android"
        IOS_BUILD_DIR: "$PROJECT_DIR/ios"
        EXPO_USERNAME: "webdev.faizanali@gmail.com"
        EXPO_PASSWORD: "aslkxsalkKLAMKLS021021##())@!"
      flutter: stable
      node: latest
      xcode: latest
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          yarn install

      - name: Login to Expo
        script: |
          npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

      # Removed CocoaPods install step because ios folder / Podfile not found

      - name: Build Android APK (unsigned)
        script: |
          cd $PROJECT_DIR
          expo build:android -t apk --non-interactive

      - name: Build iOS app (unsigned)
        script: |
          cd $PROJECT_DIR
          expo build:ios --non-interactive

    artifacts:
      - dist/*.apk
      - dist/*.ipa
