workflows:
  expo-ios-production:
    name: Expo iOS Production Build
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      vars:
        XCODE_WORKSPACE: "ios/simple-ios-todo.xcworkspace"
        XCODE_SCHEME: "simple-ios-todo"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "1"  # Added default build number
      node: 22
      xcode: 15.0
      cocoapods: default

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: Check versions
        script: |
          echo "Node version: $(node -v)"
          echo "npm version: $(npm -v)"
          echo "yarn version: $(yarn -v)"

      - name: Install dependencies
        script: |
          echo "--- Installing dependencies with Yarn Classic ---"
          yarn install --network-timeout 600000
          if [ $? -ne 0 ]; then
            echo "Failed to install dependencies"
            exit 1
          fi

      - name: Install EAS CLI
        script: |
          echo "--- Installing EAS CLI ---"
          npm install -g eas-cli@latest
          export PATH=$PATH:$(npm config get prefix)/bin
          echo "EAS CLI version: $(eas --version)"

      - name: Expo Prebuild
        script: |
          echo "--- Generating iOS Native Code ---"
          npx eas-cli@latest prebuild --platform ios --non-interactive
          if [ $? -ne 0 ]; then
            echo "Prebuild failed"
            exit 1
          fi

      - name: Install CocoaPods
        script: |
          echo "--- Installing Pods ---"
          cd ios
          pod install --repo-update --verbose
          if [ $? -ne 0 ]; then
            echo "Pod installation failed"
            exit 1
          fi

      - name: Configure Build
        script: |
          echo "--- Configuring Build ---"
          cd ios
          agvtool new-version -all $BUILD_NUMBER
          if [ $? -ne 0 ]; then
            echo "Build configuration failed"
            exit 1
          fi

      - name: Build IPA
        script: |
          echo "--- Building Production IPA ---"
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release" \
            --disable-codesigning
          if [ $? -ne 0 ]; then
            echo "IPA build failed"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/**/*.dSYM

    publishing:
      scripts:
        - name: Clean up build artifacts
          script: rm -rf ios/build
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"