workflows:
  expo-ios-development:
    name: Expo iOS Development Build
    instance_type: mac_mini_m1
    working_directory: .
    environment:
      vars:
        XCODE_WORKSPACE: "ios/simple-ios-todo.xcworkspace"
        XCODE_SCHEME: "simple-ios-todo"
        BUNDLE_ID: "com.anonymous.simpleiostodo"
        BUILD_NUMBER: "1"
        RUBY_CONFIGURE_OPTS: "--with-openssl-dir=$(brew --prefix openssl@3)"
      node: 20
      xcode: 15.0
      ruby: 3.1.4
      cocoapods: 1.14.2

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - node_modules
        - .yarn/cache
        - .yarn/install-state.gz
        - .yarn/unplugged

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "master*"
          include: true
          source: true

    scripts:
      - name: System Dependencies
        script: |
          echo "--- Installing system dependencies ---"
          brew update
          brew install openssl@3 readline libyaml gmp
          brew link openssl@3 --force
          echo "--- OpenSSL paths ---"
          ls -la $(brew --prefix openssl@3)/lib
          ls -la $(brew --prefix openssl@3)/include
          brew cleanup
          # Ensure Xcode command line tools are installed and license accepted
          xcode-select --install || true
          sudo xcodebuild -license accept || true

      - name: Install Ruby 3.1.4
        script: |
          echo "--- Installing Ruby 3.1.4 with OpenSSL path ---"
          export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3) --with-opt-dir=$(brew --prefix openssl@3)"
          export LDFLAGS="-L$(brew --prefix openssl@3)/lib"
          export CPPFLAGS="-I$(brew --prefix openssl@3)/include"
          export PKG_CONFIG_PATH="$(brew --prefix openssl@3)/lib/pkgconfig"
          echo "RUBY_CONFIGURE_OPTS: $RUBY_CONFIGURE_OPTS"
          echo "LDFLAGS: $LDFLAGS"
          echo "CPPFLAGS: $CPPFLAGS"
          rbenv install -s 3.1.4 || {
            echo "--- Build failed, trying with verbose output ---"
            rbenv install -v 3.1.4
          }
          rbenv global 3.1.4
          ruby -v

      - name: Verify Ruby Installation
        script: |
          if ! ruby -v; then
            echo "Ruby installation failed!"
            exit 1
          fi
          gem install bundler

      - name: Install Dependencies
        script: |
          echo "--- Cleaning caches ---"
          npm cache clean --force
          yarn cache clean
          echo "--- Installing dependencies ---"
          yarn install --network-timeout 600000 --frozen-lockfile

      - name: EAS CLI Setup
        script: |
          npm install -g eas-cli@latest
          eas --version

      - name: Expo Prebuild
        script: |
          echo "--- Generating native code ---"
          npx expo prebuild --platform ios --non-interactive
          echo "--- iOS directory structure ---"
          ls -la ios/

      - name: CocoaPods Setup
        script: |
          echo "--- Updating CocoaPods ---"
          sudo gem install cocoapods -v 1.14.2
          pod setup --verbose
          echo "--- Pod environment ---"
          pod env

      - name: Pod Installation
        script: |
          echo "--- Preparing Pods ---"
          cd ios
          pod cache clean --all
          rm -rf Pods Podfile.lock
          echo "--- Podfile Content ---"
          cat Podfile || echo "No Podfile found"
          echo "--- Installing Pods ---"
          pod install --repo-update --verbose
          echo "--- Pods directory ---"
          ls -la Pods/
          cd ..

      - name: Xcode Build
        script: |
          echo "--- Building archive ---"
          mkdir -p build
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/simple-ios-todo.xcarchive \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=YES

          echo "--- Exporting IPA ---"
          xcodebuild -exportArchive \
            -archivePath build/simple-ios-todo.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/export

          echo "--- Build artifacts ---"
          ls -la build/export/

    artifacts:
      - build/export/*.ipa
      - build_logs/**/*
      
    publishing:
      email:
        recipients:
          - webdev.faizanali@gmail.com
      slack:
        channel: "#build-notifications"